### ISSUE TITLE
Feature Request: Add Rich Presence status

### ISSUE THREAD

**Issue by AWL-Gaming** [BladeRavinger/Satisfactory-Discord-Hub#1]
Hello,
Would it be possible to add the current online players amount to the bot's Rich Presence status?
An example of this implementation can be found at: https://github.com/DJWoodZ/Satisfactory-Discord-Bot
![image](https://github.com/user-attachments/assets/fb316bc9-b9a6-4934-a41d-209b9a3b610b)

**Comment by BladeRavinger** [comment]
I had not thought about it till now as we have multiple servers, but of course we will get to work on that for the next update.

**Comment by SG1CSIfan** [comment]
Feature added. 
![RichPresenceImage](https://github.com/user-attachments/assets/ec471224-ae23-425c-af2f-610285f98dc5)
