### ISSUE TITLE
[Bug] Add more required discord config to .env

### ISSUE THREAD

**Issue by blockofdynamite** [BladeRavinger/Satisfactory-Discord-Hub#2]
The bot worked for the status when starting it up, but commands would not work until I added the following to the .env

```
clientId=[my clientID here]
guildId=[my guildID here]
```

Otherwise, great bot and I think it's really neat!

**Comment by BladeRavinger** [comment]
Requiring `clientID` and `guildID` is generally a dev thing.
 
As far as I understand it, the current config of the bot using the `appID` registers commands 'globally' meaning the bot can join any server and work, but this takes discord up to 10 mins to update. (as far as I have read)

Using Client/Guild ID's registers the commands only for the client and guild, and is generally faster to update via the discordAPI.

Adding `clientID` & `guildID` to the .env shouldn't change anything at all as the variables are not used anywhere in the bot.

Please give more feedback such as an error you received so we can check it out.

Thanks

**Comment by BladeRavinger** [comment]
Unable to recreate the issue + no feedback = no issue?

**Comment by blockofdynamite** [comment]
It has been a total of two business days, I've been a little busy. Anyway, It _was_ throwing an error about the missing clientID and guildID before I added them to my .env. I believe it was discord.js that was complaining, resulting in slash commands not working. Only the initial server status message would work when the bot would start, and that's it. However, at this point commands will work, but not the initial bot start server status message. It says server status embed posted successfully, but it does not. That's a different issue though, and this one can indeed be closed I guess, it might've just been a temporary discord issue.
